#! /bin/tcsh -f

# This the main NetMHCIIpan 3.0 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2013 Oct 29	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCIIpan 3.0 directory (mandatory)
setenv	NMHOME	/opt/netMHCIIpan-3.0

# determine where to store temporary files (must be writable to all users)

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /tmp
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv PLATFORM $NMHOME/$PLATFORM
setenv NETMHCIIpan $NMHOME

# main ========================================================================
if ( ! -e $NETMHCIIpan/$PLATFORM ) then
   echo netMHCIIpan: no binaries found for $PLATFORM
   exit

endif

if ( -x $NETMHCIIpan/src/NetMHCIIpan-3.0.pl ) then
   $NETMHCIIpan/src/NetMHCIIpan-3.0.pl $*
   #$NETMHCIIpan/src/NetMHCIIpan-3.0.pl $argv[1] $argv[2] $argv[3] > $argv[4]
else
   echo NetMHCIIpan-3.0.pl not found
endif



# end of script ===============================================================
